apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- token: abcdef.0123456789abcdef
ttl: 24h0m0s
localAPIEndpoint:
  advertiseAddress: 192.168.56.51
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.aliyuncs.com/google_containers
kubernetesVersion: 1.21.0
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: 192.168.0.0/16
